# Generated by Django 4.2 on 2023-04-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='id',
            new_name='uid',
        ),
    ]
