# Generated by Django 3.2.12 on 2023-04-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_id_bookinstance_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='uid',
            new_name='id',
        ),
    ]
